FROM node:20-alpine AS builder
RUN apk add --no-cache git python3 make g++
WORKDIR /app
RUN git clone https://github.com .
RUN npm rc set fetch-retry-maxtimeout 600000 && npm install --legacy-peer-deps
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV PORT=7860
ENV NODE_ENV=production
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/build ./build
COPY --from=builder /app/public ./public
RUN chown -R 1000:1000 /app
USER 1000
EXPOSE 7860
CMD ["node", "build/server/index.js"]
